# Generated by Django 5.1.1 on 2024-10-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
