# Generated by Django 5.1.1 on 2024-10-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0002_alter_data_table_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='likelihood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='pestle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_table',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
